included:
  - MilujiPraci
opt_in_rules:
  - closure_end_indentation
  - explicit_init
  - fatal_error_message
  - first_where
  - implicit_return
  - multiline_parameters
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - vertical_parameter_alignment_on_call
  - empty_count
  - force_unwrapping
  - number_separator
disabled_rules:
  - discarded_notification_center_observer
